# Generated by Django 3.2.6 on 2023-01-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('is_first_time_to_check_bmi', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=200)),
                ('how_many_times_u_checked_your_bmi_here', models.CharField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three'), ('more than 3 times', 'more than 3!!')], max_length=200)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
