# Generated by Django 3.2.6 on 2023-01-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bmi_App', '0002_remove_customer_how_many_times_u_checked_your_bmi_here'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
