# Generated by Django 3.2.6 on 2023-01-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bmi_App', '0003_auto_20230115_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_first_time_to_check_bmi',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
