# Generated by Django 3.2.6 on 2023-02-01 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bmi_App', '0005_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
